name: Release

on:
  push:
    branches: [ ci/semantic-release ]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Build
        run: yarn install --frozen-lockfile
      - run: yarn verify
      - run: yarn build
      - run: yarn test
      - name: Release
        run: yarn semantic-release --branches ci/semantic-release
